project_id = "wjxbabjwibgoihxjcpyx"

[functions.send-welcome-email]
verify_jwt = true

[functions.send-broadcast-email]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.password-reset]
verify_jwt = false

[functions.create-doku-payment]
verify_jwt = true

[functions.doku-notification]
verify_jwt = false