// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: ctx.isAuthenticated() ? { headers: { Authorization: `Bearer ${ctx.getToken()}` } } : void 0,
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List NORTHVEIZ products available in the store, with stock and price.",
  inputSchema: {
    search: z.string().optional().describe("Filter by name (case-insensitive substring)."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    const sb = client(ctx);
    let q = sb.from("products").select("id,name,price,image,stock,stock_status,description").limit(limit ?? 50);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { products: data } };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: ctx.isAuthenticated() ? { headers: { Authorization: `Bearer ${ctx.getToken()}` } } : void 0,
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Get full detail for a single NORTHVEIZ product by id, including per-size stock.",
  inputSchema: { product_id: z2.string().min(1).describe("Product id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ product_id }, ctx) => {
    const { data, error } = await client2(ctx).from("products").select("*").eq("id", product_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { product: data } };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "List my orders",
  description: "List orders belonging to the signed-in NORTHVEIZ user (most recent first).",
  inputSchema: { limit: z3.number().int().min(1).max(50).optional().describe("Max rows (default 20).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("orders").select("id,order_number,product_name,size,quantity,total_amount,payment_status,order_status,tracking_number,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { orders: data } };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_my_profile_default = defineTool4({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's NORTHVEIZ profile (name, email, phone, birthday).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("profiles").select("id,full_name,phone,birthday,avatar_url").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const merged = { ...data ?? { id: ctx.getUserId() }, email: ctx.getUserEmail() };
    return { content: [{ type: "text", text: JSON.stringify(merged) }], structuredContent: { profile: merged } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wjxbabjwibgoihxjcpyx";
var mcp_default = defineMcp({
  name: "northveiz-mcp",
  title: "NORTHVEIZ",
  version: "0.1.0",
  instructions: "Tools for the NORTHVEIZ streetwear shop. Use `list_products`/`get_product` to browse the catalog. Authenticated users can call `list_my_orders` and `get_my_profile` to inspect their own account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_product_default, list_my_orders_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
